export const products = [
  {
    id: 1,
    name: 'Organic Apples',
    slug: 'organic-apples',
    price: 20.99,
    sale_price: 18.99,
    review: 45,
    ratings: 4.7,
    until: '2024-12-31',
    stock: 15,
    top: true,
    featured: false,
    new: true,
    short_desc: true,
    category: [
      { name: 'Fruits', slug: 'fruits' },
      { name: 'Organic', slug: 'organic' },
    ],
    pictures: [
      { width: 500, height: 500, url: '/assets/images/products/prod-1.png' },
      { width: 500, height: 500, url: '/assets/images/products/prod-2.png' },
    ],
    sm_pictures: [
      {
        width: 100,
        height: 100,
        url: '/assets/images/products/prod-1.png',
      },
      {
        width: 100,
        height: 100,
        url: '/assets/images/products/prod-2.png',
      },
    ],
    variants: [
      { color: '#FF0000', color_name: 'Red', price: 18.99 },
      { color: '#FFA500', color_name: 'Orange', price: 19.99 },
    ],
    sold: 10,
  },
  {
    id: 2,
    name: 'Whole Grain Bread',
    slug: 'whole-grain-bread',
    price: 5.99,
    sale_price: null,
    review: 25,
    ratings: 4.3,
    until: null,
    stock: 0, // Out of Stock
    top: false,
    featured: true,
    new: false,
    short_desc: true,
    category: [{ name: 'Bakery', slug: 'bakery' }],
    pictures: [
      { width: 500, height: 500, url: '/assets/images/products/prod-3.png' },
    ],
    sm_pictures: [
      {
        width: 100,
        height: 100,
        url: '/assets/images/products/prod-3.png',
      },
    ],
    variants: [],
    sold: 30,
  },
  {
    id: 3,
    name: 'Fresh Salmon',
    slug: 'fresh-salmon',
    price: 25.99,
    sale_price: 22.99,
    review: 78,
    ratings: 4.9,
    until: null,
    stock: 5,
    top: true,
    featured: true,
    new: true,
    short_desc: true,
    category: [{ name: 'Seafood', slug: 'seafood' }],
    pictures: [
      { width: 500, height: 500, url: '/assets/images/products/prod-4.png' },
    ],
    sm_pictures: [
      {
        width: 100,
        height: 100,
        url: '/assets/images/products/prod-4.png',
      },
    ],
    variants: [],
    sold: 50,
  },
  {
    id: 4,
    name: 'Cheddar Cheese',
    slug: 'cheddar-cheese',
    price: 10.99,
    sale_price: null,
    review: 12,
    ratings: 4.0,
    until: null,
    stock: 25,
    top: false,
    featured: false,
    new: true,
    short_desc: true,
    category: [
      { name: 'Dairy', slug: 'dairy' },
      { name: 'Cheese', slug: 'cheese' },
    ],
    pictures: [
      { width: 500, height: 500, url: '/assets/images/products/prod-5.png' },
    ],
    sm_pictures: [
      {
        width: 100,
        height: 100,
        url: '/assets/images/products/prod-5.png',
      },
    ],
    variants: [],
    sold: 15,
  },
  {
    id: 5,
    name: 'Greek Yogurt',
    slug: 'greek-yogurt',
    price: 6.49,
    sale_price: null,
    review: 32,
    ratings: 4.5,
    until: null,
    stock: 40,
    top: false,
    featured: true,
    new: true,
    short_desc: true,
    category: [
      { name: 'Dairy', slug: 'dairy' },
      { name: 'Yogurt', slug: 'yogurt' },
    ],
    pictures: [
      { width: 500, height: 500, url: '/assets/images/products/prod-6.png' },
    ],
    sm_pictures: [
      {
        width: 100,
        height: 100,
        url: '/assets/images/products/prod-6.png',
      },
    ],
    variants: [],
    sold: 20,
  },
  {
    id: 6,
    name: 'Almond Milk',
    slug: 'almond-milk',
    price: 4.99,
    sale_price: null,
    review: 22,
    ratings: 4.2,
    until: null,
    stock: 50,
    top: true,
    featured: false,
    new: false,
    short_desc: true,
    category: [
      { name: 'Dairy', slug: 'dairy' },
      { name: 'Vegan', slug: 'vegan' },
    ],
    pictures: [
      { width: 500, height: 500, url: '/assets/images/products/prod-7.png' },
    ],
    sm_pictures: [
      {
        width: 100,
        height: 100,
        url: '/assets/images/products/prod-7.png',
      },
    ],
    variants: [],
    sold: 35,
  },
  {
    id: 7,
    name: 'Beef Steaks',
    slug: 'beef-steaks',
    price: 29.99,
    sale_price: 26.99,
    review: 65,
    ratings: 4.8,
    until: null,
    stock: 20,
    top: true,
    featured: true,
    new: true,
    short_desc: true,
    category: [{ name: 'Meat', slug: 'meat' }],
    pictures: [
      { width: 500, height: 500, url: '/assets/images/products/prod-8.png' },
    ],
    sm_pictures: [
      {
        width: 100,
        height: 100,
        url: '/assets/images/products/prod-8.png',
      },
    ],
    variants: [],
    sold: 15,
  },
  {
    id: 8,
    name: 'Honey Jar',
    slug: 'honey-jar',
    price: 12.49,
    sale_price: 9.99,
    review: 80,
    ratings: 4.9,
    until: '2025-01-01',
    stock: 100,
    top: false,
    featured: false,
    new: true,
    short_desc: true,
    category: [
      { name: 'Pantry', slug: 'pantry' },
      { name: 'Natural', slug: 'natural' },
    ],
    pictures: [
      { width: 500, height: 500, url: '/assets/images/products/prod-9.png' },
    ],
    sm_pictures: [
      {
        width: 100,
        height: 100,
        url: '/assets/images/products/prod-9.png',
      },
    ],
    variants: [],
    sold: 50,
  },
  {
    id: 9,
    name: 'Free-Range Eggs',
    slug: 'free-range-eggs',
    price: 3.99,
    sale_price: null,
    review: 50,
    ratings: 4.6,
    until: null,
    stock: 75,
    top: true,
    featured: false,
    new: false,
    short_desc: true,
    category: [
      { name: 'Dairy', slug: 'dairy' },
      { name: 'Eggs', slug: 'eggs' },
    ],
    pictures: [
      { width: 500, height: 500, url: '/assets/images/products/prod-10.png' },
    ],
    sm_pictures: [
      {
        width: 100,
        height: 100,
        url: '/assets/images/products/prod-10.png',
      },
    ],
    variants: [],
    sold: 25,
  },
  {
    id: 10,
    name: 'Dark Chocolate',
    slug: 'dark-chocolate',
    price: 7.99,
    sale_price: 6.49,
    review: 100,
    ratings: 5.0,
    until: null,
    stock: 30,
    top: true,
    featured: true,
    new: true,
    short_desc: true,
    category: [
      { name: 'Snacks', slug: 'snacks' },
      { name: 'Chocolate', slug: 'chocolate' },
    ],
    pictures: [
      { width: 500, height: 500, url: '/assets/images/products/prod-11.png' },
    ],
    sm_pictures: [
      {
        width: 100,
        height: 100,
        url: '/assets/images/products/prod-11.png',
      },
    ],
    variants: [],
    sold: 40,
  },
  {
    id: 11,
    name: 'Bananas',
    slug: 'bananas',
    price: 1.99,
    sale_price: null,
    review: 60,
    ratings: 4.7,
    until: null,
    stock: 100,
    top: false,
    featured: true,
    new: false,
    short_desc: true,
    category: [{ name: 'Fruits', slug: 'fruits' }],
    pictures: [
      { width: 500, height: 500, url: '/assets/images/products/prod-12.png' },
    ],
    sm_pictures: [
      {
        width: 100,
        height: 100,
        url: '/assets/images/products/prod-12.png',
      },
    ],
    variants: [],
    sold: 70,
  },
  {
    id: 12,
    name: 'Whole Wheat Pasta',
    slug: 'whole-wheat-pasta',
    price: 3.49,
    sale_price: null,
    review: 42,
    ratings: 4.5,
    until: null,
    stock: 40,
    top: false,
    featured: false,
    new: true,
    short_desc: true,
    category: [{ name: 'Pantry', slug: 'pantry' }],
    pictures: [
      { width: 500, height: 500, url: '/assets/images/products/prod-13.png' },
    ],
    sm_pictures: [
      {
        width: 100,
        height: 100,
        url: '/assets/images/products/prod-13.png',
      },
    ],
    variants: [],
    sold: 30,
  },
  {
    id: 13,
    name: 'Green Tea',
    slug: 'green-tea',
    price: 8.99,
    sale_price: null,
    review: 35,
    ratings: 4.3,
    until: null,
    stock: 60,
    top: true,
    featured: false,
    new: false,
    short_desc: true,
    category: [
      { name: 'Beverages', slug: 'beverages' },
      { name: 'Tea', slug: 'tea' },
    ],
    pictures: [
      { width: 500, height: 500, url: '/assets/images/products/prod-14.png' },
    ],
    sm_pictures: [
      {
        width: 100,
        height: 100,
        url: '/assets/images/products/prod-14.png',
      },
    ],
    variants: [],
    sold: 40,
  },
  {
    id: 14,
    name: 'Peanut Butter',
    slug: 'peanut-butter',
    price: 5.99,
    sale_price: 4.99,
    review: 52,
    ratings: 4.6,
    until: null,
    stock: 35,
    top: true,
    featured: true,
    new: true,
    short_desc: true,
    category: [{ name: 'Pantry', slug: 'pantry' }],
    pictures: [
      { width: 500, height: 500, url: '/assets/images/products/prod-15.png' },
    ],
    sm_pictures: [
      {
        width: 100,
        height: 100,
        url: '/assets/images/products/prod-15.png',
      },
    ],
    variants: [],
    sold: 20,
  },
];



